// Mocks generated by Mockito 5.4.6 from annotations
// in posha/test/unit/bloc/favorites_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:posha/data/models/recipe_model.dart' as _i4;
import 'package:posha/data/repository/recipe_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeRepository extends _i1.Mock implements _i2.RecipeRepository {
  MockRecipeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RecipeModel>> searchByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchByName, [query]),
            returnValue: _i3.Future<List<_i4.RecipeModel>>.value(
              <_i4.RecipeModel>[],
            ),
          )
          as _i3.Future<List<_i4.RecipeModel>>);

  @override
  _i3.Future<List<_i4.RecipeSummaryModel>> filterByArea(String? area) =>
      (super.noSuchMethod(
            Invocation.method(#filterByArea, [area]),
            returnValue: _i3.Future<List<_i4.RecipeSummaryModel>>.value(
              <_i4.RecipeSummaryModel>[],
            ),
          )
          as _i3.Future<List<_i4.RecipeSummaryModel>>);

  @override
  _i3.Future<_i4.RecipeModel?> getRecipeById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [id]),
            returnValue: _i3.Future<_i4.RecipeModel?>.value(),
          )
          as _i3.Future<_i4.RecipeModel?>);

  @override
  _i3.Future<List<_i4.CategoryModel>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i3.Future<List<_i4.CategoryModel>>.value(
              <_i4.CategoryModel>[],
            ),
          )
          as _i3.Future<List<_i4.CategoryModel>>);

  @override
  _i3.Future<List<_i4.AreaModel>> getAreas() =>
      (super.noSuchMethod(
            Invocation.method(#getAreas, []),
            returnValue: _i3.Future<List<_i4.AreaModel>>.value(
              <_i4.AreaModel>[],
            ),
          )
          as _i3.Future<List<_i4.AreaModel>>);

  @override
  _i3.Future<List<_i4.RecipeSummaryModel>> filterByCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#filterByCategory, [category]),
            returnValue: _i3.Future<List<_i4.RecipeSummaryModel>>.value(
              <_i4.RecipeSummaryModel>[],
            ),
          )
          as _i3.Future<List<_i4.RecipeSummaryModel>>);

  @override
  _i3.Future<List<_i4.RecipeModel>> getFullRecipesFromSummaries(
    List<_i4.RecipeSummaryModel>? summaries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFullRecipesFromSummaries, [summaries]),
            returnValue: _i3.Future<List<_i4.RecipeModel>>.value(
              <_i4.RecipeModel>[],
            ),
          )
          as _i3.Future<List<_i4.RecipeModel>>);
}
